web:
  build: .
  command: gunicorn -k gevent -w 1  -b 0.0.0.0:8088 --pythonpath falcon_webserver route:api 
  ports:
    - "8088:8088"
  volumes:
    - .:/backend
  links:
    - db
db:
  image: mongo:3.4.2
