# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='account.proto',
  package='account',
  syntax='proto2',
  serialized_pb=_b('\n\raccount.proto\x12\x07\x61\x63\x63ount\"]\n\x16RegisterAccountRequest\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x10\n\x08password\x18\x02 \x02(\t\x12\r\n\x05\x65mail\x18\x03 \x02(\t\x12\x14\n\x0c\x64isplay_name\x18\x04 \x01(\t\">\n\x17RegisterAccountResponse\x12#\n\x04\x63ode\x18\x01 \x02(\x0e\x32\x15.account.ResponseCode\"\x84\x01\n\x12GetAccountResponse\x12\x0f\n\x07user_id\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x14\n\x0c\x64isplay_name\x18\x03 \x02(\t\x12\r\n\x05\x65mail\x18\x04 \x02(\t\x12\x18\n\x10\x65xternal_user_id\x18\x05 \x01(\t\x12\x10\n\x08password\x18\x06 \x01(\t*9\n\x0cResponseCode\x12\x06\n\x02OK\x10\x00\x12\x0e\n\nDUPLICATED\x10\x01\x12\x11\n\rUNKNOWN_ERROR\x10\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_RESPONSECODE = _descriptor.EnumDescriptor(
  name='ResponseCode',
  full_name='account.ResponseCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DUPLICATED', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_ERROR', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=320,
  serialized_end=377,
)
_sym_db.RegisterEnumDescriptor(_RESPONSECODE)

ResponseCode = enum_type_wrapper.EnumTypeWrapper(_RESPONSECODE)
OK = 0
DUPLICATED = 1
UNKNOWN_ERROR = 3



_REGISTERACCOUNTREQUEST = _descriptor.Descriptor(
  name='RegisterAccountRequest',
  full_name='account.RegisterAccountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='account.RegisterAccountRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='account.RegisterAccountRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='email', full_name='account.RegisterAccountRequest.email', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='display_name', full_name='account.RegisterAccountRequest.display_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=119,
)


_REGISTERACCOUNTRESPONSE = _descriptor.Descriptor(
  name='RegisterAccountResponse',
  full_name='account.RegisterAccountResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='account.RegisterAccountResponse.code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=183,
)


_GETACCOUNTRESPONSE = _descriptor.Descriptor(
  name='GetAccountResponse',
  full_name='account.GetAccountResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='account.GetAccountResponse.user_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='account.GetAccountResponse.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='display_name', full_name='account.GetAccountResponse.display_name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='email', full_name='account.GetAccountResponse.email', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='external_user_id', full_name='account.GetAccountResponse.external_user_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='account.GetAccountResponse.password', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=318,
)

_REGISTERACCOUNTRESPONSE.fields_by_name['code'].enum_type = _RESPONSECODE
DESCRIPTOR.message_types_by_name['RegisterAccountRequest'] = _REGISTERACCOUNTREQUEST
DESCRIPTOR.message_types_by_name['RegisterAccountResponse'] = _REGISTERACCOUNTRESPONSE
DESCRIPTOR.message_types_by_name['GetAccountResponse'] = _GETACCOUNTRESPONSE
DESCRIPTOR.enum_types_by_name['ResponseCode'] = _RESPONSECODE

RegisterAccountRequest = _reflection.GeneratedProtocolMessageType('RegisterAccountRequest', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERACCOUNTREQUEST,
  __module__ = 'account_pb2'
  # @@protoc_insertion_point(class_scope:account.RegisterAccountRequest)
  ))
_sym_db.RegisterMessage(RegisterAccountRequest)

RegisterAccountResponse = _reflection.GeneratedProtocolMessageType('RegisterAccountResponse', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERACCOUNTRESPONSE,
  __module__ = 'account_pb2'
  # @@protoc_insertion_point(class_scope:account.RegisterAccountResponse)
  ))
_sym_db.RegisterMessage(RegisterAccountResponse)

GetAccountResponse = _reflection.GeneratedProtocolMessageType('GetAccountResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETACCOUNTRESPONSE,
  __module__ = 'account_pb2'
  # @@protoc_insertion_point(class_scope:account.GetAccountResponse)
  ))
_sym_db.RegisterMessage(GetAccountResponse)


# @@protoc_insertion_point(module_scope)
